### ISSUE TITLE
Formato de dados e arquivos JSON

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#1]
Pensando no uso dos diferentes sistemas:
Datatables
Timeline
Leaflet
Chart.JS ou D3.JS

Considerar uso de um arquivo para Tabela/Visualização
Considerar a organização em pastas, múlitplos arquivos, ec.

**Comment by gabrielfedel** [comment]
==O quê fiz:==
Limpei os json que não são necessários
Criei um arquivo README explicando o quê faz cada arquivo

==O quê falta fazer==
Separar o datatable.json dos outros json, visto que é um json estático
Organizar os dados nos seguintes arquivos:

ipes.json => dados das ipes + dados dos polos
cursos.json => dados sobre os cursos (para o datatable)
linha.json => dados de linha do tempo

**Comment by gabrielfedel** [comment]
linha.json => é possível unificar todos em um único JSON, para isso usar o exemplo 
https://github.com/tamielbr/Ciclope/blob/master/testes/timeline.html
com um arquivo similar à esse:
https://github.com/tamielbr/Ciclope/blob/master/testes/example.json

onde o "teste" poderia ser a sigla da universidade

**Comment by gabrielfedel** [comment]
cursos.json => é possível unificar todos os dados dos cursos em um único json (para o datatable), para isso é só fazer como o exemplo:
https://github.com/tamielbr/Ciclope/blob/master/testes/datatable.html
e os dados:
https://github.com/tamielbr/Ciclope/blob/master/testes/cursos_uff.json

**Comment by gabrielfedel** [comment]
Depois de analisar melhor, não acho que vale a pena juntar o ipes.json e o polos.json (pelo menos não agora).
Como resultado final vamos ter 4 arquivos de dados:
ipes.json
polos.jpsn
cursos.json
linha.json

**Comment by gabrielfedel** [comment]
@tamielbr , você já pode criar o arquivo cursos.json, que terá os dados de datatable unificados, no formato deste : https://github.com/tamielbr/Ciclope/blob/master/testes/cursos_uff.json
Assim que estiver pronto, eu modifico todos os html para aceitar o novo formato (o uff.html já está configurado como exemplo)

**Comment by gabrielfedel** [comment]
@tamielbr , também pode criar o arquivo linhas.json, que terá os dados de linha do tempo unificado, no formato deste: https://github.com/tamielbr/Ciclope/blob/master/testes/linha_ufop_nova.json

Com ele criado, modifico os html para utiliza-lo (o ufop.html já está configurado como exemplo)

**Comment by tamielbr** [comment]
Beleza. Vamos usar esse modelo.
