### ISSUE TITLE
Colocar menu para "sobre"

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#12]
Pode dar load em um único HTML que tenha informações sobre o grupo e o projeto.
Podemos usar algo como esse ícone: http://www.bistal.se/img/mobile-menu-icon.png

**Comment by gabrielfedel** [comment]
![menu](https://cloud.githubusercontent.com/assets/2080121/10473975/d6e8e590-7207-11e5-9617-d87a871490b8.png)

**Comment by gabrielfedel** [comment]
Fiz, porém estou tendo problema quando se passa o mouse no menu e a barra lateral está aberta (ele joga a barra lateral para baixo) :

![menu-erro](https://cloud.githubusercontent.com/assets/2080121/10474001/09e473b0-7208-11e5-9427-5125e25c8b12.png)

**Comment by gabrielfedel** [comment]
resolvido
