### ISSUE TITLE
Problemas nos pins dos polos

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#16]
Quando uma IPES  (1) está clicada (e seus polos aparecem), clicar em oura IPES (2) não removem o da IPES (1). Isso estava "resolvido" com os múltiplos seletores, mas agora não está. De qualquer maneira precisamos de algo mais sustentável.

![screen shot 2015-10-14 at 10 10 14](https://cloud.githubusercontent.com/assets/3904166/10484531/e2c8090a-725b-11e5-9cf1-4f364d93fe78.png)

**Comment by gabrielfedel** [comment]
Isso apareceu para mim algumas vezes durante o processo de desenvolvimento, mas depois não aconteceu mais, continua acontecendo depois que acertou os arquivos json?

**Comment by tamielbr** [comment]
O problema básico eu consegui resolver mudando a ordem, os comandos de `map.removeLayer` antes, fazem com que tudo fucione.
