### ISSUE TITLE
Problema na página "grupo"

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#17]
Se clico no Menu -> Grupo, a aba abre corretamente.
Se na sequência clicar numa IPES (só parece ser problema na UFPA), aparece, na aba, o conteúdo do "grupo". @gabrielfedel vc tenta replicar?

**Comment by gabrielfedel** [comment]
não consegui replicar o problema =(

pode dizer o passa-a-passo pra quê ele aconteça?

**Comment by gabrielfedel** [comment]
O problema é o "toggle" , quando se clica em um pin, depois da página do grupo, e depois no pin de novo, ele da hide no sidebar, e quando vc clica de novo nele, ela dá show, mas sem carregar os dados...
preciso pensar em uma solução pra isso

**Comment by gabrielfedel** [comment]
Resolvido
