### ISSUE TITLE
"X" aparece em cima do texto

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#18]
Nas páginas "sobre"

![screen shot 2015-10-14 at 10 36 09](https://cloud.githubusercontent.com/assets/3904166/10485239/7c9ee276-725f-11e5-90d2-019f9479e8cf.png)

**Comment by gabrielfedel** [comment]
@tamielbr pode confirmar se ainda acontece esse erro
não está acontecendo aqui na minha máquina nos 2 navegadores

**Comment by tamielbr** [comment]
Parece que sumiu. Resolvido.
