### ISSUE TITLE
Os pins parecem não estar exatamente no ponto que descrevem

### ISSUE THREAD

**Issue by gabrielfedel** [tamielbr/Ciclope#19]
Alguns como da UFSC estão caindo no mar, alguma configuração de margem deve estar gerando isso

**Comment by tamielbr** [comment]
É algo que vejo nos Leaflets da vida. Se vc dá zoom, fica bom? Para mim foi a solução... não sei se é algo que pode ser resolvido mas podemos jogar num fórum se for só no "zoom out".

**Comment by gabrielfedel** [comment]
Ah não, tá certo, eu bobiei, é que no mapa traçado não tem Florianópolis, quando coloco o mapa do osm fica certo
