### ISSUE TITLE
Definir proposta de layout

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#2]
Possibilidades:
- Continua abrindo lateral, mas dentro tem abas para (1) Dados, (2) Cursos e (3) Timeilne
- Abre janelas separadas para cada função

Pensar nos dados "sobre" o projeto (abre janela inicial?)

**Comment by gabrielfedel** [comment]
No https://github.com/tamielbr/Ciclope/blob/master/testes/timeline-inferior.html fiz um exemplo para utilizar o timeline na linha inferior carregando todos os timelines quando a página é carregada

**Comment by gabrielfedel** [comment]
Pensei em jogar tudo pra esquerda com ícones (como a figura abaixo), e inserir 1 ícone acima do controle de zoom, que fosse pra abrir o menu com Projeto e Sobre

![mapa-uab](https://cloud.githubusercontent.com/assets/2080121/10429626/504a405c-70d0-11e5-9311-5455a32bded8.png)

**Comment by gabrielfedel** [comment]
Estou fazendo testes com a timeline inferior, mas estou achando que ocupa muito da tela:

![mapa-uab2](https://cloud.githubusercontent.com/assets/2080121/10429671/a3771962-70d0-11e5-8721-4f6f872c013c.png)

**Comment by gabrielfedel** [comment]
Pensei em deixar a barra lateral com a fonte menor (como a imagem abaixo) e reduzir o seu tamanho também (atualmente está 50% da tela, talvez jogar para 40% ou 35%)

![mapa-uab3](https://cloud.githubusercontent.com/assets/2080121/10429907/6a1cc3fe-70d2-11e5-8f76-860380e1f866.png)

**Comment by gabrielfedel** [comment]
Além disso, pensei em colocar o logo da uab no canto inferior esquerdo do mapa (não sei se faz sentido, caso ele fique "embedado" em outro site)

**Comment by tamielbr** [comment]
@gabrielfedel vamos trabalhar com 3 tabs:
- Descritivo
- Dados
- Linha do tempo
  Ver se conseguimos fazer um seletor dinâmico em `jquery` para não ter que puxar os dados.

**Comment by gabrielfedel** [comment]
Abas - Ok

Datatable - OK (é necessário se carregar o json inteiro no começo, e ele "desenha" o datatable quando se clica na aba, caso já não tenha criado anteriormente)

Timeline - Problema com o height, está carregando errado na primeira vez, e depois acerta...

**Comment by gabrielfedel** [comment]
Resolvido o layout em abas, só falta remover os dados de timeline e datatable dos html's

**Comment by gabrielfedel** [comment]
feito
