### ISSUE TITLE
Otimizar o switch entre visualização de polos

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#21]
Esse esquema é problemático:

>  if (ipes.properties.Sigla == "UFF") {
>      map.hasLayer(UFF) ? ("", sidebar.toggle() ) : (map.addLayer(UFF), sidebar_load());
>      map.hasLayer(UFMT) ? map.removeLayer(UFMT) : "";
>      map.hasLayer(UFOP) ? map.removeLayer(UFOP) : "";
>      map.hasLayer(UFPA) ? map.removeLayer(UFPA) : "";
>      map.hasLayer(UFC) ? map.removeLayer(UFC) : "";
>      }

Nem mexi nisso (adicionei conteúdo) porque as permutações ficam punk. Vamos deixar esse como maior prioridade para resolver logo?

**Comment by gabrielfedel** [comment]
Consegui resolver isso, está com um pequeno bug em alguns casos que desconfio ter a ver com a Issue #25 (pois está emitindo a mesma mensagem)
