### ISSUE TITLE
Otimizar entrada de dados do index.html

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#22]
- Adicionar `<table id="table_data_NOME`
- div `id="timeline-NOME" class="timelines">`<br>

Como o conteúdo repete, deve ser possível rodar um `while` que verifique a existência do nome no `ipes.json` e gere o código em `jquery`. Como o nome é chave (e.g. UFSC, UFOP), deve ser fácil de montar isso.

**Comment by gabrielfedel** [comment]
foi
