### ISSUE TITLE
Otimizar dados do app.js para IPES novas

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#23]
Toda vez que criamos algo novo temos que entrar com esses dados
- `var NOME = L.geoJson(null,`
- `var polos = L.layerGroup([UFMT,UFF,UFOP,UFPA,NOME);`
- `case "NOME": UFMT.addData(val); break;`

Nesses eu acho que poderíamos rodar a IPES.JSON (tentei fuçar na var `ipes` mas ainda estou cru em acessar dados de um array json!) e popular um `array`, ou seja, os `var` e o `case` podem ser criados passando pelos nomes de IPES disponíveis.

**Comment by gabrielfedel** [comment]
eu resolvi um pouco deste problema, a única parte que não está resolvido é o primeiro item (que é atribuir o L.geojson.., pra cada ipes na mão), está ligado com o a issue #21

**Comment by gabrielfedel** [comment]
Foi
