### ISSUE TITLE
Linha do tempo não troca dados quando ponto é clicado

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#25]
Quando estou com a janela aberta em uma linha do tempo, e clico em outra IPES os dados não mudam. Mesmo se fecho a janela, quando clico em outra IPES, os dados da IPES1 (priimeira a ser clicada, aparecem). Mandei vídeo por email.

**Comment by tamielbr** [comment]
Validei o JSON da timeline, tudo ok. Adicionei os dados no index.html. Se quiser verificar já está sync no github.

**Comment by tamielbr** [comment]
No console dá erro em: 
`$('#table_data_'+thisIpes.toLowerCase()).dataTable( {` -> _datatable is not a function_

**Comment by gabrielfedel** [comment]
Tel, não estou conseguindo replicar esse erro, vc falou que mandou um vídeo, não estou encontrando, poderia me passar de novo?

**Comment by tamielbr** [comment]
@gabrielfedel mandei!

**Comment by gabrielfedel** [comment]
Opa, ví aqui
que estranho, está acontecendo só com alguns pontos, vou verificar o quê pode ser

**Comment by gabrielfedel** [comment]
Resolvido,
o problema era o fato dos html das ipes carregar o jquery novamente (se carrega ele mais de uma vez gera problemas)
