### ISSUE TITLE
Colocar todos os dados da IPES no Json

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#26]
Pensar em transferir os dados padrão (nome, endereço, telefone) do HTML para o `ipes.json`

**Comment by tamielbr** [comment]
Já coloquei um exemplo dos dados no JSON para testarmos.

**Comment by tamielbr** [comment]
Formato fechado.

**Comment by gabrielfedel** [comment]
Fiz uma versão na UEl, pode dar uma olhada pra ver se é isso mesmo? se estiver ok, vou replicar pras outras

**Comment by tamielbr** [comment]
Ficou bom! Acho que depois pode der uma bonitada no CSS, mas pegou os dados certinho ao que parece.
