### ISSUE TITLE
Timeline com imagem cobre o texto

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#27]
No tamanho que temos hoje, há problema no tamanho da imagem. Mexer no CSS do timeline resolve (`max-width` que está _inline_) mais ou menos, mas o ideal era uma imagem escalada, menor (%), mas não sei se é recomendado. Antes:

![screen shot 2015-10-15 at 20 43 24](https://cloud.githubusercontent.com/assets/3904166/10530355/7cba91e6-737d-11e5-914f-366aa71f4566.png)

Depois:

![screen shot 2015-10-15 at 20 43 32](https://cloud.githubusercontent.com/assets/3904166/10530356/812bf7ce-737d-11e5-89c9-c2ffd1d5a047.png)

As opções do [timeilne.js](https://github.com/NUKnightLab/TimelineJS3) permitem fazer o timiline `portrait` usando `layout:  "landscape",    // portrait or landscape`. Isso poderia ser interessante (é o nosso caso, tela comprida), mas tentei e nada acontece. Não sei se por acaso você customizou algum CSS.

Essa linha do tempo (`ead_uab.json`) é a timeline que vamos usar para a UAB como um todo, no site. Deixei ela aqui no Github se quiser renomear para `linhas.json` e testar (clicando na UFF).

**Comment by gabrielfedel** [comment]
Hum... não consegui replicar esse erro, aqui está aparecendo ok: 
![problem-timeline](https://cloud.githubusercontent.com/assets/2080121/10892653/d49befec-818b-11e5-898f-0e387fbd9a21.png)

**Comment by tamielbr** [comment]
@gabrielfedel vc tentou com browsers diferentes? Podemos ver aqui.

**Comment by gabrielfedel** [comment]
Testei no firefox e chrome, mas podemos ver juntos sim

**Comment by tamielbr** [comment]
Pode ser relacionado a #29, testar depois de resolver isso.

**Comment by tamielbr** [comment]
Deixou de ser problema.
