### ISSUE TITLE
Pegar JSON mapa do Brasil com estados

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#3]
IBGE creio que tem

**Comment by tamielbr** [comment]
Uma opção: https://github.com/carolinabigonha/br-atlas

**Comment by gabrielfedel** [comment]
Tentei utilizar esse mas tive problemas com o node, vou tentar novamente 

aparentemente o geojson gerado possuí todos os estados (talvez até municípios), pode ser que fique muito pesado pra quê queremos

verificar outras soluções

**Comment by tamielbr** [comment]
@gabrielfedel podemos mandar email no fórum do http://forum.openstreetmap.org/ perguntando como extrair isso?

**Comment by tamielbr** [comment]
Encontrei, e testei 1 estado, funcionou. Estou arrumando os dados. Precisa ver se fica pesado no final. Posto aqui quando der certo.

https://github.com/nvkelso/natural-earth-vector/tree/master/geojson

**Comment by tamielbr** [comment]
Feito, farei sync logo mais.
