### ISSUE TITLE
Não exibe todos os polos

### ISSUE THREAD

**Issue by gabrielfedel** [tamielbr/Ciclope#34]
Quando se clica no botão lateral não se exibe todos os polos
O problema está ocorrendo no seguinte trecho:

allLayers[val.properties.ipes].addData(val);

ele não consegue adicionar os pontos pois o allLayers ainda não está todo carregado

**Comment by gabrielfedel** [comment]
Não tenho mais certeza se o problema é o assincronismo
consegui remover a mensagem de erro gerado neste ponto:

allLayers[val.properties.ipes].addData(val);

mas aparentemente não é isso que está gerando o problema

**Comment by gabrielfedel** [comment]
Estou adicionando os pontos de uma maneira diferente, aparentemente a camada de polos está ok, porém quando se seleciona ela, vem um erro do leaflet:

TypeError: t.onAdd is not a function

**Comment by tamielbr** [comment]
Quando dá erro assim é sempre bom validar o JSON (http://jsonformatter.curiousconcept.com/) para verificar se não é esse o problema.

**Comment by gabrielfedel** [comment]
@tamielbr , pode fazer um teste aí pra ver se os polos de cada ipes estão aparecendo quando se clica na ipes? aqui no firefox tá aparecendo, mas intermitente, as vezes rola as vezes não

**Comment by gabrielfedel** [comment]
O Formato do Json tá ok, vou continuar tentando resolver o problema

**Comment by tamielbr** [comment]
@gabrielfedel beleza. Amanhã a tarde vou fechar os HTMLs e vou enviar para o pessoal dar uma olhada (mando só a noite). Se conseguir fuçar até lá, seria bacana!

**Comment by tamielbr** [comment]
Testei rapidamente, clicando em cada, e abrindo/fechando aba, e parece ok. Podemos depois continuar observando - um jeito é fazer o "tooltip" do polo (o que abre quando clica) mostrar a IPES. assim podemos saber se os polos que estão ligados a IPES aparecem. No geral, parece ok.

**Comment by gabrielfedel** [comment]
Ufa, resolvi!
