### ISSUE TITLE
Identiticar todos os polos ativos da UAB

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#37]

**Comment by tamielbr** [comment]
@gabrielfedel podemos fazer um pedido de acesso a informação, que acha? Algo como:

Planilha em formato aberto (e.g. CSV, ODT ou Excel) em que conste:
1. Nome do polo
2. Logradouro do polo
3. Cidade do polo
4. Estado do polo
5. CEP do polo
6. Número de cursos ativos
7. Siglas ou nomes das Instituições de Ensino Superior que atualmente oferecem cursos no polo

**Comment by gabrielfedel** [comment]
Acho uma ótimo ideia!

**Comment by tamielbr** [comment]
Faltou tempo, vou tentar fazer isso até semana que vem, mas no próximo encontro podemos usar `http://webscraper.io`.

**Comment by tamielbr** [comment]
Pedido feito (LAI): 23480.017810/2015-30

**Comment by tamielbr** [comment]
LAI respondido com dados incompletos mas suficientes.
