### ISSUE TITLE
Explorar funcionalidade e formato do Timeline.JS v3

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#4]
Verificar se formato JSON é igual ao v2

**Comment by gabrielfedel** [comment]
Não é igual, o formato é esse:
https://github.com/NUKnightLab/TimelineJS3/blob/master/website/templates/examples/houston/timeline3.json

acho que vale a pena já mudar, visto que com o uso do timelinejs v3 conseguimos unificar os arquivos json de linha do tempo em um único (não consegui achar documentação da versão 2 pra saber se é possível também com ela)

**Comment by tamielbr** [comment]
Vamos de v3, fechado.
