### ISSUE TITLE
Datatables fica no "responsive" mesmo em tela cheia

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#40]
![screen shot 2015-11-13 at 20 09 09](https://cloud.githubusercontent.com/assets/3904166/11158898/76ab618c-8a42-11e5-9fac-11284e55a50e.png)

**Comment by tamielbr** [comment]
Me parece que os dados aparecem errados também, tudo separado por vírgula...

**Comment by gabrielfedel** [comment]
Era um problema no json, resolvido
