### ISSUE TITLE
Rever o código HTML de construção de tabela

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#42]
Acho que isso aqui poderia usar `$.each(data.features, function (key, val) {...` 
no `index.html`

Mais elegante, não é?

**Comment by gabrielfedel** [comment]
Não sei se entendi, já estamos usando $.each pra carregar os dados do datatable, era essa a sugestão?

**Comment by tamielbr** [comment]
@gabrielfedel desculpe, não ficou claro - era aqui `var theadDefault = "<thead><tr><th class=\"dt-left\">Nome</th>` pegando key,val. assim fica menos "hardcoded".

**Comment by gabrielfedel** [comment]
Tel, 
eu acho que esses dados não estão em nenhum json (o "cabeçalho": nome, tipo, chamada , etc..)

ou eu que entendi errado?

**Comment by tamielbr** [comment]
Pois é, por isso pensei em duas coisas:
- Será que vale a pena um JSON pra isso?
- Será que não dá pra separar o `html` (`th`, etc) dos dados para que se alguem for customizar, ficar mais fácil?

**Comment by gabrielfedel** [comment]
Inserir essa informação dentro do cursos.json

**Comment by gabrielfedel** [comment]
Fazer assim

>   "header" :[
>     "Nome",
>     "Tipo",
>     "Chamada",
>     "Carga horária",
>     "Períodos"
>   ],
>   "cursos" : {"UFF":{

**Comment by gabrielfedel** [comment]
Foi
