### ISSUE TITLE
Testar Chart.js com dados de um dos datatables de IPES

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#43]
Em `testes/ipes` coloquei o mapa dos NEADs extraído. Podemos testar o `chart.js` aqui, fazendo um pie-chart com quantas ipes temos por estado e depois por região (podemos editar o JSON se for o caso), por exemplo. 

_Veja que há um problema quando temos dois vector layers, tem que clicar 2x no menu para aparecer as IPES por cima, problema que só será resolvido no Leaflet 1.0 - depois faço teste no beta, por hora deixamos ou eliminamos o mapa dos estados._

**Comment by gabrielfedel** [comment]
@tamielbr , só pra confirmar, onde você pensou em colocar esse gráfico nessa parte de teste?
em cima do mapa?

ps: esse problema que citou não consegui visualizar :/

**Comment by tamielbr** [comment]
Poderia ser algo que fica em cima do mapa por hora, no canto vazio. No Ciclope, eu imagino que teremso que ter o conteúdo numa aba. Mas sabendo como funciona, podemos replicar. O passo mais importante acho que é fazer uso do mesmo `json` do datatables para o chart.js, se possível, sem ter que passar por uma transformação de dados. Mas se for necessário, sem problemas. Acho que precisamos mais é de um demo por hora e saber que funciona, depois definimos o que queremos em termos de dados/gráficos.

Quanto ao problema, que bom. Podemos ver isso junto, mas aqui aparece e parece nos fóruns do Leaflet. Podemos ignorar por hora.

**Comment by gabrielfedel** [comment]
@tamielbr  fiz um teste funcional, dê um olhada

Deixei marcado no código o quê eu precisei fazer para gerar o gráfico, tive que montar "na mão" os dados que vão ser usados no gráfico de pizza

O esquema de cores precisa melhorar, mas achei melhor subir assim mesmo pra ver, pois de certo modo, praticamente não utilizamos os dados do json diretamente, e sim um conjunto de dados resultantes da manipulação... acha que isso é um problema? se não for, sigo assim. 
Um ponto pra comentar, é que se formos dessa maneira, pra cada tipo de gráfico que quisermos, precisaremos de um código pra gerar os dados para o gráfico.

**Comment by tamielbr** [comment]
Finalizado.
