### ISSUE TITLE
Chart dos dados do Ciclope-NEAD

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#45]
Somente uma pizza: número de polos por estado, para cada NEAD, que deve aparecer na aba principal.

**Comment by gabrielfedel** [comment]
Fiz um teste na UFMT (print abaixo), pelo jeito que fiz teria que inserir o código em cada html, mantemos assim?

é só esse gráfico mesmo certo?

Ainda preciso melhorar o esquema de cores

![captura de tela - 15-12-2015 - 11 49 52](https://cloud.githubusercontent.com/assets/2080121/11812267/0ce23a3e-a322-11e5-9ee3-a2e578ccc334.png)
