### ISSUE TITLE
Rever nomes de todos os arquivos

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#47]
Renomear os arquivos para facilitar entendimento do que faz o que

**Comment by tamielbr** [comment]
@gabrielfedel  fazer uma lista prévia e eu fecho!

**Comment by gabrielfedel** [comment]
Pasta json -> data

Pasta uab:
app.js -> ciclope.js
mover os 2 .json para data/geo/
index.html
ipesfunctions.js
u*.html -> mover para content

pasta testes/ipes mudar para /ipes (na raiz)

O resto acho que tá ok (a pasta testes podemos remover depois)

**Comment by tamielbr** [comment]
Revendo:
app.js -> ciclope.js 
mover os 2 .json para /geo/
ipesfunctions.js vira functions.js
mover functions.js e ciclope.js para /js
u*.html -> mover para content

**Comment by gabrielfedel** [comment]
foi
