### ISSUE TITLE
Adicionar descritivos claros para cada arquivo no GitHub

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#48]

**Comment by tamielbr** [comment]
@gabrielfedel quando estiver pronto pra fazer, eu ajudo a descrever.

**Comment by gabrielfedel** [comment]
Acho que é melhor resolver o #47 antes

**Comment by gabrielfedel** [comment]
a gente usa o br_pais.json?

**Comment by tamielbr** [comment]
Não. Esse é uma versão simples (outline) do país. Vou backup aqui, podemos remover.

**Comment by tamielbr** [comment]
Finalizado, um readme por pasta.
