### ISSUE TITLE
Selecionar programa de gráficos

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#5]
D3 ou Chart.JS

**Comment by tamielbr** [comment]
@gabrielfedel lembando que a ideia é que o programa possa dialogar com o datatables. Talvez isso tenha impacto no modelo de dados (JSON) que vamos usar. Talvez seja útil verificar rapidamente o Chart ou o D3 para saber que modelo de dados eles precisam. Pelo que notei, pro que queremos talvez o Chart seja mais simples (http://www.chartjs.org/).

**Comment by gabrielfedel** [comment]
O melhor é o chart.js mesmo (o D3 é de uso bem mais genérico, e é necessário, de certa forma, implementar o código para gerar o gráfico)
Subi um arquivo com teste dele

De todo modo, vamos precisar manipular o json para passar as informações que vamos exibir, pois ele esperar informações como a cor de cada "pedaço" do gráfico (dependendo do tipo

**Comment by tamielbr** [comment]
@gabrielfedel onde está o arquivo/teste?

**Comment by gabrielfedel** [comment]
https://github.com/tamielbr/Ciclope/tree/master/testes/chartjs

**Comment by tamielbr** [comment]
Ok linkei isso com #43.
