### ISSUE TITLE
Remover os .JSON do Github

### ISSUE THREAD

**Issue by gabrielfedel** [tamielbr/Ciclope#50]
Jogar os .json no servidor da uab, e no código puxar de lá

**Comment by gabrielfedel** [comment]
@tamielbr antes de eu retirar eles daqui, o ideal seria você subir eles no servidor da uab, pode fazer isso?

**Comment by tamielbr** [comment]
@gabrielfedel  Feito. Atualizei o site com a última versão do repo.

**Comment by gabrielfedel** [comment]
Legal, só me confirma o caminho que ficaram os json? (o ideal seria fora do caminho de onde está o código, para quando mudar o caminho no código e remover os json do repositório, não remover do servidor também)

**Comment by tamielbr** [comment]
`http://uab.educacaoaberta.org/apps/nead/json/`

**Comment by gabrielfedel** [comment]
Hum, é um pouco mais complicado do quê parece, dá um probleminha por ser de um domínio diferente: http://stackoverflow.com/questions/3506208/jquery-ajax-cross-domain

**Comment by tamielbr** [comment]
Lembro disso. Mas na verdade o nosso problema é só remover o JSON do github. Pensando bem, @gabrielfedel , nem vejo problema em deixar ai. São dados abertos, e quem baixar vai ver tudo. Mas por outro lado pode ser pesado. Podemos, deixar por hora, e eliminar num lançamento `beta` talvez deixando só uma coisa ou outra online para mostrar funcionalidade.

**Comment by gabrielfedel** [comment]
Blz
Na verdade pensei em tirar mais pra deixar limpo mesmo (talvez mais coerente), mas acho que pode ser algo pra ficar pra depois mesmo, sem crise

**Comment by tamielbr** [comment]
Decidimos manter.
