### ISSUE TITLE
Melhorar Gráficos NEAD

### ISSUE THREAD

**Issue by gabrielfedel** [tamielbr/Ciclope#52]
Melhorar disposição e desempenho

**Comment by tamielbr** [comment]
**Centralizar tudo**

**Pizza**
- Colocar título nos gráficos em pizza
- Colocar texto (título + porcentagem) permanentes, não `mouse-over` em pizza
- Diminuir o tamanho (também no Ciclope, para ocupar menos espaço

**Barra**
 Dar um sort por quantidade no gráfico de barras

**Comment by gabrielfedel** [comment]
Fiz,
porém o título permanente fica muito poluído, @tamielbr dê um olhada

**Comment by tamielbr** [comment]
Rever se é possível colocar o texto para fora do chart.

**Comment by gabrielfedel** [comment]
Aparentemente não é possível sem reprogramar parte do chart.js :(

acho que as possibilidades mais simples são:
mudar os estados pra sigla e/ou aumentar o tamanho do gráfico

Talvez mudar o tipo de gráfico resolva também, mas não sei fica bom (o quê está agora parece ser o melhor para esses dados)

**Comment by tamielbr** [comment]
Que pena. Acho:
1. Mudar pra sigla é uma boa, pra começar e ver o que acontece.
2. O tamanho do gráfico, se precisar.
3. Por último, mudar o tipo de gráfico se for o caso.

**Comment by gabrielfedel** [comment]
Estou fazendo uns testes, e aparentemente 1 e 2 não vão resolver, 

queria fazer isso:

http://jsfiddle.net/TZq6q/1/

Mas não está rolando por causa da maneira como carrego os dados para o gráfico
vou tentar mais um pouco ainda

**Comment by tamielbr** [comment]
Vamos seguir com a ideia de uma legenda, ao lado direito do gráfico conforme o fiddle acima.

**Comment by gabrielfedel** [comment]
foi
