### ISSUE TITLE
Definir uso de JSON, noSQL ou DB tradicional

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#60]

**Comment by gabrielfedel** [comment]
@tamielbr pelo que eu dei uma lida e comentada, parece que noSql não é muito adequado pra esses dados (http://stackoverflow.com/questions/10553860/nosql-use-case-scenarios-or-when-to-use-nosql https://www.mongodb.com/use-cases http://programmers.stackexchange.com/questions/273340/when-to-use-a-nosql-database-such-as-mongodb-over-mysql http://www.informationweek.com/big-data/software-platforms/when-nosql-makes-sense/d/d-id/1111811? )

entre os pontos que mais vejo necessidade em usar um bd é o lance dos joins (pra conseguir alguns tipos de informações que precisamos), e esse é um dos principais pontos que o nosql não faz normalmente

dado as coisas que estamos querendo "extrair" dos dados como estão, me parece melhor usar um bd tradicional

**Comment by tamielbr** [comment]
Vamos testar relacional e ver onde chegamos.

**Comment by tamielbr** [comment]
MySQL. Feito.
