### ISSUE TITLE
Conversor CSV-JSON para Timeline.JS v3

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/Ciclope#7]
Criar um aplicativo web/Python que podemos hospedar no ASO para converter CSV padrão do Timeline.JS v3 para o JSON apropriado.
- Conversor geral
- Conversor para o projeto, que inclua (1) Upload de vários arquivos usando (2) o nome como "chave"

**Comment by gabrielfedel** [comment]
@tamielbr 
Talvez isso resolva:
http://www.convertcsv.com/csv-to-json.htm

tem alguma planilha disponível para testarmos?

**Comment by gabrielfedel** [comment]
Neste link: http://www.convertcsv.com/csv-to-json.htm

Usando essa regra:

Top
{lb} "events": [{br}

Repeating Section for each Line of CSV

  {lb}
     "start_date" : {
     "year":{(f1)==""?"\"\"":f1}
    ,"month":{(f2)==""?"\"\"":f2}
    ,"day":{(f3)==""?"\"\"":f3} } ,
    "end_date" : {
    "year":{(f4)==""?"\"\"":f4}
    ,"month":{(f5)==""?"\"\"":f5}
    ,"day":{(f6)==""?"\"\"":f6} 
    ,"display_date":"{f7}" }
    , "text" : {
    "headline":"{f8}"
    ,"text":"{f9}" },
    "media" : {
    "url":"{f10}"
    ,"credit":"{f11}"
    ,"caption":"{f12}"
    ,"thumbnail":"{f13}" },  
    "group":"{f14}"
    ,"background":"{f15}"
  {rb}

Bottom

]  {rb}

E Usando o seguinte arquivo como modelo:

https://github.com/tamielbr/Ciclope/blob/master/models/template-timeline.ods

**Comment by tamielbr** [comment]
Ajustes:

O script inclui o `header` mesmo que o conteúdo seja vazio. Como no nosso caso só estamos usando dois campos (ano, headline e texto) acaba ficando excessivo (ele coloca tudo, `credit`, `thumbnail` etc mesmo que seja vazio). 

Para agora, ficou melhor assim:

> {lb}
> "start_date" : {
> "year":"{(f1)==""?"\"\"":f1}"
> }
> ,"text":{
> "headline":"{f8}"
> ,"text":"{f9}" }
> {rb}

**Comment by tamielbr** [comment]
Acho que seria o caso, depois com tempo, de montar um script-zinho que fosse mais prático e verificassse se ``null`. Você avaliaria o tempo necessário para criar algo, para pensarmos se/quando vale a pena?

**Comment by tamielbr** [comment]
@gabrielfedel será que rolaria um "upload" no tab que permite que a pessoa coloque o CSV bem formatado e já aparece lá o timeline, por exemplo?

**Comment by gabrielfedel** [comment]
Depois de funcionar, fazer uma plataforma para conversão online

**Comment by gabrielfedel** [comment]
Feito! está em python por hora na pasta csvtojsontimeline, modo de uso:

python csvtojsontime.py modelo.csv "Texto de headline" "Título"
- Texto de headline e título são fixos, do slide "zero"

E ele gera um arquivo result.json com o resultado da conversão

**Comment by tamielbr** [comment]
Eu testo ele e retorno com feedback.

**Comment by tamielbr** [comment]
@gabrielfedel funcionando. Próximos passos que falamos:
- Tentar fechar todos os campos
- Separar em um repositório próprio e divulgar pro pessoal do TimelineJS

**Comment by gabrielfedel** [comment]
mudei ele pro gitlab: 
https://gitlab.com/fedel/csvtojsontimelinejs

**Comment by tamielbr** [comment]
Trabalhando com issues no GitLab. Fechamos essa quando estiver finalizado lá.

**Comment by gabrielfedel** [comment]
Issues no git lab, seguir por lá
